description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4.1.0
      with:
        version: 10.18.2
    - uses: actions/setup-node@v5.0.0
      with:
        node-version: '22.20.0'
        cache: pnpm
    - run: pnpm install
      shell: bash
  using: composite
