description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: 8
    - uses: actions/setup-node@v3.8.1
      with:
        node-version: '18.x'
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite