description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4.1.0
      with:
        version: 10
    - uses: actions/setup-node@v4.3.0
      with:
        node-version: '20.x'
        cache: pnpm
    - run: pnpm install
      shell: bash
  using: composite
